#!/bin/sh

_bro () {
  echo 1 = $1
  echo 2 = $2
  echo 3 = $3
  echo COMP_LINE = $COMP_LINE
  echo COMP_POINT = $COMP_POINT
  echo COMP_KEY = $COMP_KEY
  echo COMP_TYPE = $COMP_TYPE
  echo COMP_WORDS = ${COMP_WORDS[]}
  echo COMP_CWORD = $COMP_CWORD
  local cur
  COMREPLY=()
  cur=$2

  case "$cur" in
    -*)
      COMPREPLY=( $( compgen -W '-t -p -r' -- $cur ) )
      ;;
    *)
      COMPREPLY=( $(compgen -W 'create delete' -- $cur) )
    ;;
  esac
}

complete -F _bro bro