#!/bin/sh

create_tasks_file() {
	if [ ! $1  ]; then
		echo "Please pass file name."
		return 0
	fi

	cat > .brotasks/$1 << 'EOF'
def init():
	print("Happy hacking")
EOF

	chmod +x .brotasks/$1

}

get_tasks() {
	file=$1
	tasks="$(bro_sed -nr  's/def\s*([a-zA-Z][a-zA-Z0-9_]*)\s*\(.*\)\s*:\s*$/\1/p' $file)"
	echo "$tasks"
}

execute_task() {
	file=$1
	task=$2

	pattern="s/def\s*($task)\s*\(.*\)\s*:\s*$/\1/p" 
	match="$(bro_sed -nr $pattern $file)" 
	if [ $task = "$match" ] ; then
		shift
		shift
		params="$(echo $@ | bro_sed -r 's/[a-z]+/"&"/g')"
		params="$(echo $params | bro_sed -e 's/\s/,/g')"

		python -c "exec(open('$file').read()); $task($params)"
	fi
}

$@
