#!/bin/bash

get_tasks() {
	file=$1
	tasks="$(sed -n  's/\s*\([a-zA-Z][a-zA-Z0-9_]*\)\s*(\s*)\s*{\s*$/\1/p' $file)"
	echo "$tasks"
}

execute_task() {
	file=$1
	task=$2

	pattern="s/\s*\($task\)\s*(\s*)\s*{\s*$/\1/p" 
	match="$(sed -n $pattern $file)" 
	if [ $task == "$match" ] ; then
		$@
	fi
}

$@
