#!/bin/sh

project=$1
shift
full_cmd=$@
task=$1

case $task in
  setup)
    # Edit this section for setting up a project.
    # Commands here are executed only during project creation.
    # 'bro create <project>' executes commands here.

    # git
    git init
    echo '.brofile' >> .gitignore

    # setup virtual environment with default python version
    virtualenv .env
    echo '.env' >> .gitignore
    source .env/bin/activate

    # install django and create app
    pip install django
    django-admin startproject $2 .

    # boot project
    source .brofile $project boot
    ;;
  boot)
    # Edit this section to launch necessary tools for a project.
    # Commands here are the first to be executed during project startup.
    # 'bro <project> boot' executes commands here.

    source .brofile $project workon

    # launch necessary tools
    # subl &
    # firefox &
    # nemo &
    ;;
  workon)
    # Edit this section to set appropriate environment for the project."
    # Commands here are to be executed for every new terminals.
    # 'bro <project> workon' executes commands here.

    # activate the virtual env
    source .env/bin/activate
    ;;
  *)
    bro_usage
 esac
