#!/bin/sh

project=$1
shift
full_cmd=$@
task=$1

case $task in
  setup)
    # Edit this section for setting up a project.
    # Commands here are executed only during project creation.
    # 'bro create <project>' executes commands here.

    echo "Make sure 'nvm' is installed. If not get it with 'npm install -g nvm'."

    # git
    git init
    echo ".brofile" >> .gitignore

    # setup project
    npm init

    # boot project
    source .brofile $project boot
    ;;
  boot)
    # Edit this section to launch necessary tools for a project.
    # Commands here are the first to be executed during project startup.
    # 'bro <project> boot' executes commands here.

    source .brofile $project workon

    # launch necessary tools
    # subl &
    # firefox &
    # nemo &
    ;;
  workon)
    # Edit this section to set appropriate environment for the project."
    # Commands here are to be executed for every new terminals.
    # 'bro <project> workon' executes commands here.

    # setup node version
    nvm use 4.2.3
    ;;
  *)
    bro_usage
 esac
