#!/bin/sh

# $1 is subcommand
# $2 is project name

case $1 in
  setup)
    # Edit this section for setting up a project.
    # Commands here are executed only during project creation.
    # 'bro create <project>' executes commands here.

    # git
    git init
    echo '.brofile' >> .gitignore

    # setup virtual environment
    virtualenv --python=python2 .env
    echo '.env' >> .gitignore

    # boot project
    source .brofile boot
    ;;
  boot)
    # Edit this section to launch necessary tools for a project.
    # Commands here are the first to be executed during project startup.
    # 'bro boot <project>' executes commands here.

    source .brofile workon

    # launch necessary tools
    # subl &
    # firefox &
    # nemo &
    ;;
  workon)
    # Edit this section to set appropriate environment for the project."
    # Commands here are to be executed for every new terminals.
    # 'bro workon <project>' executes commands here.

    # activate the virtual env
    source .env/bin/activate
    ;;
  *)
    echo "Unknown command."
 esac
